### ISSUE TITLE
在字符串中使用自定义前后缀表示SpEl表达式

### ISSUE THREAD

**Issue by pqcqaq** [ly-chn/spel-extension-idea#1]
我需要在一段文本中使用SpEl表达式并通过该插件获得代码提示功能，在@Language()注解下可以加入prefix:="{{", suffix"="}}",来获得语法高亮，但是无法实现代码提示，在使用本插件的过程中发现，无法在json配置文件中加入prefix和suffix来实现自定义SpEl表达式。
例如：
![image](https://github.com/ly-chn/SpEL-Assistant/assets/35625470/c16f3ace-2cf9-4c3f-870d-aec79b2546f0)

期望的json配置文件如下：

```json
{
  "online.zust.qcqcqc.services.module.log.annotation.OperationLog@value": {
    "prefix": "{{",
    "suffix": "}}",
    "method": {
      "result": true,
      "resultName": "returnValue",
      "parameters": true,
      "parametersPrefix":[]
    }
  }
}
```

希望能够修复这个问题，感谢！

**Comment by ly-chn** [comment]
收到，后续将加入此功能

**Comment by pqcqaq** [comment]
非常感谢，希望能够尽早体验到插件的便利😄😄

**Comment by ly-chn** [comment]
@pqcqaq 非常感谢提供建议, 新版已发布待审核, 2个工作日内审核完毕, 如需尽快体验可前往 https://github.com/ly-chn/SpEL-Assistant/releases/tag/1.1.0 下载体验 , 与`@Language`的区别是: 

`@Language`的`prefix`和`suffix`为代码前缀后缀, 意思是将 `prefix+自己写的表达式+suffix` 视为完整SpEL表达式

而`SpEL Assistant`的`prefix`和`suffix`为模板前缀后缀, 意思是将`prefix`和`suffix`中间的内容视为SpEL表达式, 并忽视周围的区域

![image](https://github.com/ly-chn/SpEL-Assistant/assets/37045167/9fcd8cd5-2c64-4e13-9026-ce72704f0559)

**Comment by pqcqaq** [comment]
非常感谢，经过我一周的使用，我很喜欢这个插件带来的功能，并且已经跟我的朋友们推荐了😆😆
