### ISSUE TITLE
注册函数支持提示

### ISSUE THREAD

**Issue by Elijah-Liu** [ly-chn/spel-extension-idea#2]
如图所示，_changeName是我像StandardEvaluationContext中注册的函数，可以提供注册函数的提示吗？

![image](https://github.com/user-attachments/assets/5d797aff-6241-459d-9d60-b7d5f45e0768)

**Comment by ly-chn** [comment]
其实用自定义函数更好的方式是设置rootObject, 这篇博客是根spring security和spring cache相似度较高的实现方式, 可以参考一下: https://blog.csdn.net/xiaoyanhhh/article/details/135967040

当然如果自定义函数的话, 后续我会考虑加上
