### ISSUE TITLE
请问可以支持自定义变量么？

### ISSUE THREAD

**Issue by alchemist1234** [ly-chn/spel-extension-idea#3]
我在EvaluationContext中通过setVariable添加了几个自定义变量，在SpEL中通过"#变量名"获取到添加了变量，但好像没有看到可以配置变量提示的地方

**Comment by ly-chn** [comment]
看README中的示例, 使用fields字段即可

**Comment by ly-chn** [comment]
![image](https://github.com/user-attachments/assets/0d9b9ba2-7ebf-41b4-b902-25897c89e83d)
