### ISSUE TITLE
方法参数代码提示不符合预期

### ISSUE THREAD

**Issue by ooooym** [ly-chn/spel-extension-idea#4]
### spel-extension.json配置
![image](https://github.com/user-attachments/assets/8a99e3f8-8418-48b9-bb19-a6125e7d463d)

### 代码中的表现
* 作用的方法签名
``` java
    public ConsultationOrder create(Consultation consultation, BigDecimal orderOriginalAmount) {
       return null;
    }
```
* 表现效果一（不使用前缀）
![image](https://github.com/user-attachments/assets/1dc6a348-c02d-4468-937b-9bef55f8ddcd)

* 表现效果二（使用前缀） 
![image](https://github.com/user-attachments/assets/fd9d0dbc-3733-4192-bca7-a75002e09490)

问题：
1. 不使用任何前缀后缀配置时，代码提示正常，但是我是有配置前缀和后缀的
2. 使用spel-extension.json中配置好的前缀和后缀时，不支持代码提示

环境：IntelliJ IDEA 2024.2.1 (Ultimate Edition) + SpEL Assistant 1.2.1

**Comment by ly-chn** [comment]
收到, 将紧急修复

**Comment by ly-chn** [comment]
不好意思, 确实发现了一点小问题(空spel时会有轻微代码损耗), 但是无法复现呢
重启idea可以解决吗, 我这里可以正常提示呢
![image](https://github.com/user-attachments/assets/557f20be-e2a8-4268-a64e-93d6c46e4b64)
请问使用这个项目可以复现吗: https://github.com/ly-chn/spel-assistant-demo

**Comment by ooooym** [comment]
辛苦了~

刚刚尝试了重启idea和执行了File>Invalidate Cache操作，现象和之前一致

https://github.com/ly-chn/spel-assistant-demo 这个项目是不是私有的，访问提示404

**Comment by ooooym** [comment]
补充：
我这边发现，使用前缀匹配不生效的原因和我idea的一个配置有关系
![image](https://github.com/user-attachments/assets/9abce678-6004-4ca6-833a-60a0b3e542a7)

![image](https://github.com/user-attachments/assets/d1cfbb34-649a-495a-bc3a-0c65fa4bb76a)
删除此配置项以后，可以正常使用

**Comment by ly-chn** [comment]
哦哦, 原来如此, 多谢
